import { LocationMapping } from "./types"

export const locationMappings: LocationMapping[] = [
  {
    id: "loc-001",
    posLocationId: "pos-loc-001",
    posLocationName: "Main Restaurant",
    posLocationCode: "LOC001",
    carmenLocationId: "carmen-loc-001",
    carmenLocationName: "Main Dining Area",
    carmenLocationType: "Restaurant",
    isActive: true,
    syncEnabled: true,
    mappedBy: { id: "user-001", name: "Admin User" },
    mappedAt: "2023-01-15T10:00:00",
    notes: "Primary restaurant location",
  },
  {
    id: "loc-002",
    posLocationId: "pos-loc-002",
    posLocationName: "Lobby Bar",
    posLocationCode: "LOC002",
    carmenLocationId: "carmen-loc-002",
    carmenLocationName: "Hotel Lobby Bar",
    carmenLocationType: "Bar",
    isActive: true,
    syncEnabled: true,
    mappedBy: { id: "user-001", name: "Admin User" },
    mappedAt: "2023-01-15T10:05:00",
  },
  {
    id: "loc-003",
    posLocationId: "pos-loc-003",
    posLocationName: "Pool Bar",
    posLocationCode: "LOC003",
    carmenLocationId: "carmen-loc-003",
    carmenLocationName: "Swimming Pool Bar",
    carmenLocationType: "Bar",
    isActive: true,
    syncEnabled: true,
    mappedBy: { id: "user-001", name: "Admin User" },
    mappedAt: "2023-01-15T10:10:00",
  },
  {
    id: "loc-004",
    posLocationId: "pos-loc-004",
    posLocationName: "Rooftop Lounge",
    posLocationCode: "LOC004",
    carmenLocationId: "carmen-loc-004",
    carmenLocationName: "Skyview Lounge",
    carmenLocationType: "Lounge",
    isActive: false,
    syncEnabled: false,
    mappedBy: { id: "user-001", name: "Admin User" },
    mappedAt: "2023-01-15T10:15:00",
    notes: "Currently inactive",
  },
  {
    id: "loc-005",
    posLocationId: "pos-loc-005",
    posLocationName: "Beach Restaurant",
    posLocationCode: "LOC005",
    carmenLocationId: "carmen-loc-005",
    carmenLocationName: "Seaside Dining",
    carmenLocationType: "Restaurant",
    isActive: true,
    syncEnabled: true,
    mappedBy: { id: "user-002", name: "Manager User" },
    mappedAt: "2023-10-05T14:30:00",
  },
  {
    id: "loc-006",
    posLocationId: "pos-loc-006",
    posLocationName: "Cafe Corner",
    posLocationCode: "LOC006",
    carmenLocationId: "carmen-loc-006",
    carmenLocationName: "Lobby Cafe",
    carmenLocationType: "Cafe",
    isActive: true,
    syncEnabled: false,
    mappedBy: { id: "user-002", name: "Manager User" },
    mappedAt: "2023-09-20T09:15:00",
    notes: "Sync disabled due to errors",
  },
  {
    id: "loc-007",
    posLocationId: "pos-loc-007",
    posLocationName: "VIP Lounge",
    posLocationCode: "LOC007",
    carmenLocationId: "carmen-loc-007",
    carmenLocationName: "Executive Lounge",
    carmenLocationType: "Lounge",
    isActive: true,
    syncEnabled: true,
    mappedBy: { id: "user-001", name: "Admin User" },
    mappedAt: "2023-03-10T11:30:00",
  },
  {
    id: "loc-008",
    posLocationId: "pos-loc-008",
    posLocationName: "Room Service",
    posLocationCode: "LOC008",
    carmenLocationId: "carmen-loc-008",
    carmenLocationName: "In-Room Dining",
    carmenLocationType: "Service",
    isActive: true,
    syncEnabled: true,
    mappedBy: { id: "user-001", name: "Admin User" },
    mappedAt: "2023-01-15T10:20:00",
  },
]

export const posTypes = [
  { id: "comanche", name: "Comanche" },
  { id: "soraso", name: "Soraso" },
  { id: "easypos", name: "Easy POS" },
  { id: "hoteltime", name: "HotelTime" },
  { id: "infrasys", name: "Infrasys" },
]
