version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: carmen_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/New_York}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-password}
      - N8N_METRICS=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_ONBOARDING_FLOW_DISABLED=false
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_PERSISTED_BINARY_DATA_TTL=2880
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows:rw
      - ./n8n/credentials:/home/node/.n8n/credentials:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - n8n_network
      - default
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  n8n-postgres:
    image: postgres:15-alpine
    container_name: carmen_n8n_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${N8N_DB_NAME:-n8n}
      - POSTGRES_USER=${N8N_DB_USER:-n8n}
      - POSTGRES_PASSWORD=${N8N_DB_PASSWORD:-n8n_password}
      - POSTGRES_NON_ROOT_USER=${N8N_DB_USER:-n8n}
      - POSTGRES_NON_ROOT_PASSWORD=${N8N_DB_PASSWORD:-n8n_password}
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${N8N_DB_USER:-n8n} -d ${N8N_DB_NAME:-n8n}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  n8n_data:
    driver: local
  n8n_postgres_data:
    driver: local

networks:
  n8n_network:
    driver: bridge