import { RecipeCategory } from '@/lib/types'

export const mockCategories: RecipeCategory[] = [
  {
    // Base Category fields
    id: "1",
    name: "Appetizers",
    description: "Small dishes served before main courses",
    parentId: undefined,
    level: 1,
    isActive: true,
    // RecipeCategory specific fields
    code: "APP",
    defaultPrepTime: 15,
    defaultCookTime: 10,
    defaultShelfLife: 2,
    defaultStation: "Cold Station",
    defaultSkillLevel: "intermediate",
    menuSection: "Starters",
    displayOrder: 1
  },
  {
    id: "1-1",
    name: "Cold Appetizers",
    description: "Appetizers served cold or at room temperature",
    parentId: "1",
    level: 2,
    isActive: true,
    code: "APP-COLD",
    defaultPrepTime: 10,
    defaultCookTime: 0,
    defaultShelfLife: 4,
    defaultStation: "Cold Station",
    defaultSkillLevel: "beginner",
    menuSection: "Starters",
    displayOrder: 1
  },
  {
    id: "1-2",
    name: "Hot Appetizers",
    description: "Appetizers served hot",
    parentId: "1",
    level: 2,
    isActive: true,
    code: "APP-HOT",
    defaultPrepTime: 15,
    defaultCookTime: 15,
    defaultShelfLife: 1,
    defaultStation: "Hot Station",
    defaultSkillLevel: "intermediate",
    criticalControlPoints: ["Temperature control - keep above 140°F"],
    menuSection: "Starters",
    displayOrder: 2
  },
  {
    id: "2",
    name: "Main Courses",
    description: "Primary dishes for a meal",
    parentId: undefined,
    level: 1,
    isActive: true,
    code: "MAIN",
    defaultPrepTime: 20,
    defaultCookTime: 30,
    defaultShelfLife: 2,
    defaultStation: "Main Kitchen",
    defaultSkillLevel: "advanced",
    menuSection: "Entrées",
    displayOrder: 2
  },
  {
    id: "2-1",
    name: "Meat Dishes",
    description: "Main courses featuring meat as primary ingredient",
    parentId: "2",
    level: 2,
    isActive: true,
    code: "MAIN-MEAT",
    defaultPrepTime: 15,
    defaultCookTime: 35,
    defaultShelfLife: 2,
    defaultStation: "Grill Station",
    defaultSkillLevel: "advanced",
    criticalControlPoints: ["Internal temperature - minimum 165°F for poultry, 145°F for beef"],
    menuSection: "Entrées",
    displayOrder: 1
  },
  {
    id: "2-2",
    name: "Seafood",
    description: "Main courses featuring seafood",
    parentId: "2",
    level: 2,
    isActive: true,
    code: "MAIN-FISH",
    defaultPrepTime: 10,
    defaultCookTime: 20,
    defaultShelfLife: 1,
    defaultStation: "Seafood Station",
    defaultSkillLevel: "advanced",
    criticalControlPoints: ["Internal temperature - minimum 145°F", "Freshness check"],
    allergenWarnings: ["Shellfish", "Fish"],
    menuSection: "Entrées",
    displayOrder: 2
  },
  {
    id: "2-3",
    name: "Vegetarian",
    description: "Vegetarian main courses",
    parentId: "2",
    level: 2,
    isActive: true,
    code: "MAIN-VEG",
    defaultPrepTime: 20,
    defaultCookTime: 25,
    defaultShelfLife: 3,
    defaultStation: "Vegetable Station",
    defaultSkillLevel: "intermediate",
    menuSection: "Entrées",
    displayOrder: 3
  },
  {
    id: "3",
    name: "Desserts",
    description: "Sweet dishes served after main courses",
    parentId: undefined,
    level: 1,
    isActive: true,
    code: "DES",
    defaultPrepTime: 30,
    defaultCookTime: 25,
    defaultShelfLife: 24,
    defaultStation: "Pastry Station",
    defaultSkillLevel: "advanced",
    menuSection: "Desserts",
    displayOrder: 3
  },
  {
    id: "3-1",
    name: "Cakes & Pastries",
    description: "Baked desserts including cakes and pastries",
    parentId: "3",
    level: 2,
    isActive: true,
    code: "DES-CAKE",
    defaultPrepTime: 45,
    defaultCookTime: 30,
    defaultShelfLife: 48,
    defaultStation: "Pastry Station",
    defaultSkillLevel: "advanced",
    allergenWarnings: ["Gluten", "Eggs", "Dairy", "Nuts"],
    menuSection: "Desserts",
    displayOrder: 1
  },
  {
    id: "3-2",
    name: "Frozen Desserts",
    description: "Ice cream, sorbets, and frozen treats",
    parentId: "3",
    level: 2,
    isActive: true,
    code: "DES-FROZEN",
    defaultPrepTime: 15,
    defaultCookTime: 0,
    defaultShelfLife: 720, // 30 days
    defaultStation: "Pastry Station",
    defaultSkillLevel: "intermediate",
    criticalControlPoints: ["Storage temperature - maintain below 0°F"],
    allergenWarnings: ["Dairy", "Eggs"],
    menuSection: "Desserts",
    displayOrder: 2
  },
  {
    id: "4",
    name: "Beverages",
    description: "Hot and cold drinks",
    parentId: undefined,
    level: 1,
    isActive: true,
    code: "BEV",
    defaultPrepTime: 5,
    defaultCookTime: 0,
    defaultShelfLife: 2,
    defaultStation: "Bar",
    defaultSkillLevel: "beginner",
    menuSection: "Beverages",
    displayOrder: 4
  },
  {
    id: "5",
    name: "Salads",
    description: "Fresh salads and cold dishes",
    parentId: undefined,
    level: 1,
    isActive: true,
    code: "SAL",
    defaultPrepTime: 10,
    defaultCookTime: 0,
    defaultShelfLife: 4,
    defaultStation: "Cold Station",
    defaultSkillLevel: "beginner",
    criticalControlPoints: ["Wash all vegetables thoroughly", "Keep refrigerated until service"],
    menuSection: "Salads",
    displayOrder: 5
  }
]
