import { CuisineType } from '@/lib/types'

export const mockCuisines: CuisineType[] = [
  {
    id: "1",
    name: "Italian",
    code: "ITA",
    description: "Traditional Italian cuisine with regional specialties",
    region: "Europe",
    country: "Italy",
    typicalIngredients: ["Olive Oil", "Tomatoes", "Basil", "Mozzarella", "Parmesan"],
    cookingMethods: ["Baking", "Sautéing", "Boiling", "Grilling"],
    flavorProfile: ["Savory", "Herbal", "Garlic", "Umami"],
    spiceLevel: "mild",
    isActive: true,
    displayOrder: 1
  },
  {
    id: "2",
    name: "Chinese",
    code: "CHN",
    description: "Diverse Chinese culinary traditions",
    region: "Asia",
    country: "China",
    typicalIngredients: ["Soy Sauce", "Ginger", "Garlic", "Rice", "Sesame Oil"],
    cookingMethods: ["Stir-frying", "Steaming", "Deep-frying", "Braising"],
    flavorProfile: ["Savory", "Sweet", "Sour", "Umami"],
    spiceLevel: "medium",
    isActive: true,
    displayOrder: 2
  },
  {
    id: "3",
    name: "Mexican",
    code: "MEX",
    description: "Vibrant Mexican food culture",
    region: "Americas",
    country: "Mexico",
    typicalIngredients: ["Corn", "Chili", "Cilantro", "Lime", "Avocado"],
    cookingMethods: ["Grilling", "Frying", "Baking", "Braising"],
    flavorProfile: ["Spicy", "Savory", "Tangy", "Fresh"],
    spiceLevel: "hot",
    isActive: true,
    displayOrder: 3
  },
  {
    id: "4",
    name: "Indian",
    code: "IND",
    description: "Rich and diverse Indian cuisine",
    region: "Asia",
    country: "India",
    typicalIngredients: ["Spices", "Rice", "Yogurt", "Lentils", "Ghee"],
    cookingMethods: ["Curry", "Tandoor", "Frying", "Steaming"],
    flavorProfile: ["Spicy", "Aromatic", "Complex", "Rich"],
    spiceLevel: "hot",
    isActive: true,
    displayOrder: 4
  },
  {
    id: "5",
    name: "French",
    code: "FRA",
    description: "Classic French culinary arts",
    region: "Europe",
    country: "France",
    typicalIngredients: ["Butter", "Wine", "Herbs", "Cream", "Garlic"],
    cookingMethods: ["Sautéing", "Braising", "Baking", "Poaching"],
    flavorProfile: ["Rich", "Buttery", "Savory", "Herbal"],
    spiceLevel: "mild",
    isActive: true,
    displayOrder: 5
  },
  {
    id: "6",
    name: "Japanese",
    code: "JPN",
    description: "Traditional Japanese cooking methods",
    region: "Asia",
    country: "Japan",
    typicalIngredients: ["Rice", "Seaweed", "Dashi", "Soy Sauce", "Mirin"],
    cookingMethods: ["Sushi", "Tempura", "Grilling", "Simmering"],
    flavorProfile: ["Umami", "Delicate", "Savory", "Fresh"],
    spiceLevel: "mild",
    isActive: true,
    displayOrder: 6
  },
  {
    id: "7",
    name: "Mediterranean",
    code: "MED",
    description: "Healthy Mediterranean diet",
    region: "Europe",
    country: undefined,
    typicalIngredients: ["Olive Oil", "Lemon", "Chickpeas", "Tomatoes", "Feta"],
    cookingMethods: ["Grilling", "Roasting", "Baking", "Raw"],
    flavorProfile: ["Fresh", "Tangy", "Herbal", "Savory"],
    spiceLevel: "mild",
    isActive: true,
    displayOrder: 7
  },
  {
    id: "8",
    name: "Thai",
    code: "THA",
    description: "Flavorful Thai cooking traditions",
    region: "Asia",
    country: "Thailand",
    typicalIngredients: ["Lemongrass", "Coconut Milk", "Fish Sauce", "Thai Basil", "Chili"],
    cookingMethods: ["Stir-frying", "Curry", "Steaming", "Grilling"],
    flavorProfile: ["Spicy", "Sweet", "Sour", "Savory"],
    spiceLevel: "hot",
    isActive: true,
    displayOrder: 8
  },
  {
    id: "9",
    name: "American",
    code: "USA",
    description: "Diverse American culinary traditions",
    region: "Americas",
    country: "United States",
    typicalIngredients: ["Beef", "Potatoes", "Cheese", "Corn", "BBQ Sauce"],
    cookingMethods: ["Grilling", "Smoking", "Frying", "Baking"],
    flavorProfile: ["Savory", "Smoky", "Sweet", "Hearty"],
    spiceLevel: "mild",
    isActive: true,
    displayOrder: 9
  },
  {
    id: "10",
    name: "Korean",
    code: "KOR",
    description: "Traditional Korean cuisine",
    region: "Asia",
    country: "South Korea",
    typicalIngredients: ["Kimchi", "Gochujang", "Soy Sauce", "Sesame", "Rice"],
    cookingMethods: ["BBQ", "Stir-frying", "Fermenting", "Steaming"],
    flavorProfile: ["Spicy", "Savory", "Umami", "Fermented"],
    spiceLevel: "hot",
    isActive: true,
    displayOrder: 10
  }
]
