/**
 * Mock Product Data
 * Centralized product mock data for the Carmen ERP application
 */

import { Product } from '@/lib/types'

export const mockProducts: Product[] = [
  {
    id: 'product-001',
    productCode: 'OIL-OLIVE-001',
    productName: 'Premium Olive Oil',
    description: 'Extra virgin olive oil from Italy',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'cat-oils',
    specifications: [],
    baseUnit: 'bottle',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 8.50, currency: 'USD' },
    quantityDecimalPlaces: 0, // Count-based unit (bottle)
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    keywords: ['olive', 'oil', 'premium'],
    tags: ['oils', 'cooking'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'product-002',
    productCode: 'VEG-TOM-002',
    productName: 'Organic Tomatoes',
    description: 'Fresh organic roma tomatoes',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'cat-vegetables',
    specifications: [],
    baseUnit: 'kg',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 3.25, currency: 'USD' },
    quantityDecimalPlaces: 3, // Weight-based unit (kg)
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    keywords: ['tomatoes', 'organic', 'vegetables'],
    tags: ['vegetables', 'fresh'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'product-003',
    productCode: 'DRY-FLR-003',
    productName: 'All-Purpose Flour',
    description: 'High-quality all-purpose flour',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'cat-dry-goods',
    specifications: [],
    baseUnit: 'kg',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 2.10, currency: 'USD' },
    quantityDecimalPlaces: 3, // Weight-based unit (kg)
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    keywords: ['flour', 'baking', 'dry goods'],
    tags: ['dry-goods', 'baking'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'product-004',
    productCode: 'HRB-BAS-004',
    productName: 'Fresh Basil',
    description: 'Fresh organic basil leaves',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'cat-herbs',
    specifications: [],
    baseUnit: 'bunch',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 1.80, currency: 'USD' },
    quantityDecimalPlaces: 0, // Count-based unit (bunch)
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    keywords: ['basil', 'herbs', 'fresh'],
    tags: ['herbs', 'fresh'],
    regulatoryApprovals: [],
    isActive: true
  },
  // Merged from app/(main)/vendor-management/lib/mock-data.ts
  {
    id: 'beef-ribeye',
    productCode: 'BR-001',
    productName: 'Beef Ribeye Steak',
    description: 'Beef Ribeye Steak',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'food-beverage',
    specifications: [],
    baseUnit: 'kg',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' }, // Placeholder
    quantityDecimalPlaces: 3, // Weight-based unit (kg)
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    keywords: ['beef', 'ribeye', 'steak'],
    tags: ['meat-poultry', 'beef-cuts'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'chicken-breast',
    productCode: 'CB-001',
    productName: 'Chicken Breast',
    description: 'Chicken Breast',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'food-beverage',
    specifications: [],
    baseUnit: 'kg',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 3, // Weight-based unit (kg)
    keywords: ['chicken', 'breast'],
    tags: ['meat-poultry', 'poultry-fresh'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'salmon-fillet',
    productCode: 'SF-001',
    productName: 'Atlantic Salmon Fillet',
    description: 'Atlantic Salmon Fillet',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'food-beverage',
    specifications: [],
    baseUnit: 'kg',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 3, // Weight-based unit (kg)
    keywords: ['salmon', 'fillet', 'fish'],
    tags: ['seafood', 'fresh-fish'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'shrimp-jumbo',
    productCode: 'SJ-001',
    productName: 'Jumbo Shrimp',
    description: 'Jumbo Shrimp',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'food-beverage',
    specifications: [],
    baseUnit: 'kg',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 3, // Weight-based unit (kg)
    keywords: ['shrimp', 'jumbo', 'shellfish'],
    tags: ['seafood', 'shellfish'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'tomatoes-vine',
    productCode: 'TV-001',
    productName: 'Vine Tomatoes',
    description: 'Vine Tomatoes',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'food-beverage',
    specifications: [],
    baseUnit: 'kg',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 3, // Weight-based unit (kg)
    keywords: ['tomatoes', 'vine', 'vegetables'],
    tags: ['produce', 'vegetables'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'apples-gala',
    productCode: 'AG-001',
    productName: 'Gala Apples',
    description: 'Gala Apples',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'food-beverage',
    specifications: [],
    baseUnit: 'kg',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 3, // Weight-based unit (kg)
    keywords: ['apples', 'gala', 'fruit'],
    tags: ['produce', 'fruits'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'milk-whole',
    productCode: 'MW-001',
    productName: 'Whole Milk',
    description: 'Whole Milk',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'food-beverage',
    specifications: [],
    baseUnit: 'L',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 3, // Volume-based unit (L)
    keywords: ['milk', 'whole', 'dairy'],
    tags: ['dairy', 'milk-cream'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'cheddar-cheese',
    productCode: 'CC-001',
    productName: 'Cheddar Cheese',
    description: 'Cheddar Cheese',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'food-beverage',
    specifications: [],
    baseUnit: 'kg',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 3, // Weight-based unit (kg)
    keywords: ['cheese', 'cheddar', 'dairy'],
    tags: ['dairy', 'cheese'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'dish-soap',
    productCode: 'DS-001',
    productName: 'Commercial Dish Soap',
    description: 'Commercial Dish Soap',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'supplies',
    specifications: [],
    baseUnit: 'L',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 3, // Volume-based unit (L)
    keywords: ['soap', 'dish', 'cleaning'],
    tags: ['cleaning', 'detergents'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'paper-towels',
    productCode: 'PT-001',
    productName: 'Paper Towels',
    description: 'Paper Towels',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'supplies',
    specifications: [],
    baseUnit: 'pack',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 0, // Count-based unit (pack)
    keywords: ['towels', 'paper', 'disposables'],
    tags: ['disposables', 'paper-products'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'napkins',
    productCode: 'NK-001',
    productName: 'Cocktail Napkins',
    description: 'Cocktail Napkins',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'supplies',
    specifications: [],
    baseUnit: 'pack',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 0, // Count-based unit (pack)
    keywords: ['napkins', 'cocktail', 'disposables'],
    tags: ['disposables', 'paper-products'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'paper-cups',
    productCode: 'PC-001',
    productName: 'Disposable Paper Cups',
    description: 'Disposable Paper Cups',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'supplies',
    specifications: [],
    baseUnit: 'pack',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 0, // Count-based unit (pack)
    keywords: ['cups', 'paper', 'disposables'],
    tags: ['disposables', 'paper-products'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'plastic-bags',
    productCode: 'PB-001',
    productName: 'Food Storage Bags',
    description: 'Food Storage Bags',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'supplies',
    specifications: [],
    baseUnit: 'box',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 0, // Count-based unit (box)
    keywords: ['bags', 'storage', 'plastic'],
    tags: ['disposables', 'plastic-items'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'chef-knife',
    productCode: 'CK-001',
    productName: "Chef's Knife 8-inch",
    description: "Chef's Knife 8-inch",
    productType: 'raw_material',
    status: 'active',
    categoryId: 'equipment',
    specifications: [],
    baseUnit: 'piece',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 0, // Count-based unit (piece)
    keywords: ['knife', 'chef', 'kitchen'],
    tags: ['kitchen', 'prep-equipment'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'cutting-board',
    productCode: 'CB-002',
    productName: 'Commercial Cutting Board',
    description: 'Commercial Cutting Board',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'equipment',
    specifications: [],
    baseUnit: 'piece',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 0, // Count-based unit (piece)
    keywords: ['cutting board', 'kitchen', 'prep'],
    tags: ['kitchen', 'prep-equipment'],
    regulatoryApprovals: [],
    isActive: true
  },
  {
    id: 'dining-chair',
    productCode: 'DC-001',
    productName: 'Wooden Dining Chair',
    description: 'Wooden Dining Chair',
    productType: 'raw_material',
    status: 'active',
    categoryId: 'equipment',
    specifications: [],
    baseUnit: 'piece',
    alternativeUnits: [],
    isInventoried: true,
    isSerialTrackingRequired: false,
    isBatchTrackingRequired: false,
    isPurchasable: true,
    isSellable: true,
    standardCost: { amount: 0, currency: 'USD' },
    images: [],
    documents: [],
    relatedProducts: [],
    substitutes: [],
    accessories: [],
    quantityDecimalPlaces: 0, // Count-based unit (piece)
    keywords: ['chair', 'dining', 'furniture'],
    tags: ['furniture', 'dining-furniture'],
    regulatoryApprovals: [],
    isActive: true
  }
]
