/**
 * Mock Recipe Data
 * Centralized recipe mock data for the Carmen ERP application
 */

import { Recipe } from '@/lib/types'

export const mockRecipes: Recipe[] = [
  {
    id: 'recipe-001',
    recipeCode: 'RCP-001',
    name: 'Classic Margherita Pizza',
    description: 'Traditional Italian pizza with tomatoes, mozzarella, and basil',
    categoryId: 'category-001',
    cuisineTypeId: 'cuisine-001',
    status: 'published',
    complexity: 'moderate',
    yield: 4,
    yieldUnit: 'servings',
    basePortionSize: 1,
    servingSize: '1 pizza',
    yieldVariants: [
      {
        id: 'variant-001',
        name: 'Full Pizza',
        unit: 'servings',
        quantity: 4,
        conversionRate: 1.0,
        sellingPrice: { amount: 12.00, currency: 'USD' },
        costPerUnit: { amount: 3.50, currency: 'USD' },
        marginPercentage: 70.8,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-001',
        name: 'All-Purpose Flour',
        type: 'product',
        productId: 'product-003',
        quantity: 0.5,
        unit: 'kg',
        wastage: 2,
        yield: 98,
        netQuantity: 0.49,
        inventoryQty: 0.5,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 2.50, currency: 'USD' },
        totalCost: { amount: 1.25, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-002',
        name: 'Organic Tomatoes',
        type: 'product',
        productId: 'product-002',
        quantity: 0.3,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.285,
        inventoryQty: 0.3,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 1.20, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-003',
        name: 'Fresh Basil',
        type: 'product',
        productId: 'product-004',
        quantity: 1,
        unit: 'bunch',
        wastage: 10,
        yield: 90,
        netQuantity: 0.9,
        inventoryQty: 1,
        inventoryUnit: 'bunch',
        conversionFactor: 1.0,
        costPerUnit: { amount: 1.50, currency: 'USD' },
        totalCost: { amount: 1.50, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-001',
        order: 1,
        stepNumber: '1',
        title: 'Prepare Dough',
        description: 'Prepare pizza dough with flour and water',
        duration: 15,
        equipments: ['Mixing Bowl'],
        tools: ['Measuring Cup', 'Whisk'],
        isPortionable: true
      },
      {
        id: 'step-002',
        order: 2,
        stepNumber: '2',
        title: 'Roll Dough',
        description: 'Roll out dough into circle',
        duration: 5,
        equipments: ['Work Surface'],
        tools: ['Rolling Pin'],
        isPortionable: true
      },
      {
        id: 'step-003',
        order: 3,
        stepNumber: '3',
        title: 'Add Toppings',
        description: 'Add tomato sauce and mozzarella cheese',
        duration: 5,
        equipments: [],
        tools: ['Ladle', 'Spoon'],
        isPortionable: true
      },
      {
        id: 'step-004',
        order: 4,
        stepNumber: '4',
        title: 'Bake',
        description: 'Bake at 220°C for 15 minutes',
        duration: 15,
        temperature: 220,
        equipments: ['Pizza Oven'],
        tools: ['Pizza Peel'],
        isPortionable: false
      },
      {
        id: 'step-005',
        order: 5,
        stepNumber: '5',
        title: 'Garnish',
        description: 'Garnish with fresh basil',
        duration: 2,
        equipments: [],
        tools: ['Knife'],
        isPortionable: true
      }
    ],
    prepTime: 30,
    cookTime: 15,
    totalTime: 45,
    totalCost: { amount: 14.00, currency: 'USD' },
    costPerPortion: { amount: 3.50, currency: 'USD' },
    foodCostPercentage: 29.2,
    requiredEquipment: ['Pizza Oven', 'Mixing Bowl', 'Work Surface'],
    skillLevel: 'intermediate',
    allergens: [],
    dietaryRestrictions: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isHalal: false,
    isKosher: false,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Italian', 'Pizza', 'Main Course'],
    keywords: ['pizza', 'margherita', 'italian', 'tomato', 'basil'],
    developedBy: 'user-001'
  },
  {
    id: 'recipe-002',
    recipeCode: 'RCP-002',
    name: 'Mediterranean Salad',
    description: 'Fresh salad with tomatoes, olives, and olive oil dressing',
    categoryId: 'category-002',
    cuisineTypeId: 'cuisine-002',
    status: 'published',
    complexity: 'simple',
    yield: 2,
    yieldUnit: 'servings',
    basePortionSize: 1,
    servingSize: '1 bowl',
    yieldVariants: [
      {
        id: 'variant-002',
        name: 'Regular Bowl',
        unit: 'servings',
        quantity: 2,
        conversionRate: 1.0,
        sellingPrice: { amount: 8.50, currency: 'USD' },
        costPerUnit: { amount: 2.25, currency: 'USD' },
        marginPercentage: 73.5,
        isDefault: true,
        isMenuAvailable: true,
        displayOrder: 1,
        isActive: true
      }
    ],
    ingredients: [
      {
        id: 'ingredient-004',
        name: 'Organic Tomatoes',
        type: 'product',
        productId: 'product-002',
        quantity: 0.2,
        unit: 'kg',
        wastage: 5,
        yield: 95,
        netQuantity: 0.19,
        inventoryQty: 0.2,
        inventoryUnit: 'kg',
        conversionFactor: 1.0,
        costPerUnit: { amount: 4.00, currency: 'USD' },
        totalCost: { amount: 0.80, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 1
      },
      {
        id: 'ingredient-005',
        name: 'Premium Olive Oil',
        type: 'product',
        productId: 'product-001',
        quantity: 0.05,
        unit: 'bottle',
        wastage: 0,
        yield: 100,
        netQuantity: 0.05,
        inventoryQty: 0.05,
        inventoryUnit: 'bottle',
        conversionFactor: 1.0,
        costPerUnit: { amount: 15.00, currency: 'USD' },
        totalCost: { amount: 0.75, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 2
      },
      {
        id: 'ingredient-006',
        name: 'Fresh Basil',
        type: 'product',
        productId: 'product-004',
        quantity: 0.5,
        unit: 'bunch',
        wastage: 10,
        yield: 90,
        netQuantity: 0.45,
        inventoryQty: 0.5,
        inventoryUnit: 'bunch',
        conversionFactor: 1.0,
        costPerUnit: { amount: 1.50, currency: 'USD' },
        totalCost: { amount: 0.75, currency: 'USD' },
        isOptional: false,
        substitutes: [],
        displayOrder: 3
      }
    ],
    preparationSteps: [
      {
        id: 'step-006',
        order: 1,
        stepNumber: '1',
        title: 'Prepare Tomatoes',
        description: 'Dice tomatoes',
        duration: 10,
        equipments: ['Cutting Board'],
        tools: ['Chef Knife'],
        isPortionable: true
      },
      {
        id: 'step-007',
        order: 2,
        stepNumber: '2',
        title: 'Add Dressing',
        description: 'Add olive oil dressing',
        duration: 3,
        equipments: ['Mixing Bowl'],
        tools: ['Spoon'],
        isPortionable: true
      },
      {
        id: 'step-008',
        order: 3,
        stepNumber: '3',
        title: 'Garnish',
        description: 'Garnish with fresh basil',
        duration: 2,
        equipments: [],
        tools: ['Knife'],
        isPortionable: true
      },
      {
        id: 'step-009',
        order: 4,
        stepNumber: '4',
        title: 'Serve',
        description: 'Serve immediately',
        duration: 1,
        equipments: ['Serving Bowl'],
        tools: [],
        isPortionable: true
      }
    ],
    prepTime: 15,
    cookTime: 0,
    totalTime: 15,
    totalCost: { amount: 4.50, currency: 'USD' },
    costPerPortion: { amount: 2.25, currency: 'USD' },
    foodCostPercentage: 26.5,
    requiredEquipment: ['Cutting Board', 'Mixing Bowl', 'Serving Bowl'],
    skillLevel: 'beginner',
    allergens: [],
    dietaryRestrictions: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isHalal: true,
    isKosher: true,
    image: '',
    isActive: true,
    isMenuActive: true,
    version: '1.0',
    tags: ['Mediterranean', 'Salad', 'Healthy'],
    keywords: ['salad', 'mediterranean', 'tomato', 'olive oil', 'healthy'],
    developedBy: 'user-001'
  }
]