import { PurchaseRequest, PurchaseRequestItem, PRType, DocumentStatus, WorkflowStatus, WorkflowStage } from '@/lib/types'

export const samplePRData = {
  id: 'sample-pr-001',
  refNumber: 'PR-2023-001',
  date: new Date('2023-01-01'),
  type: PRType.GeneralPurchase,
  description: 'Sample purchase request for office supplies',
  requestorId: 'user-001',
  requestor: {
    name: 'John Doe',
    id: 'user-001',
    department: 'Administration'
  },
  status: DocumentStatus.Draft,
  workflowStatus: WorkflowStatus.Pending,
  currentWorkflowStage: WorkflowStage.requester,
  location: 'Head Office',
  department: 'Administration',
  jobCode: 'JOB-001',
  estimatedTotal: 1500,
  vendor: 'Office Supplies Co.',
  vendorId: 1,
  deliveryDate: new Date('2023-01-15'),
  currency: 'USD',
  baseCurrencyCode: 'USD',
  baseSubTotalPrice: 1000,
  subTotalPrice: 1000,
  baseNetAmount: 1000,
  netAmount: 1000,
  baseDiscAmount: 0,
  discountAmount: 0,
  baseTaxAmount: 100,
  taxAmount: 100,
  baseTotalAmount: 1100,
  totalAmount: 1100,
}

export const samplePRItems = [
  {
    id: "PR-2023-001-01",
    location: "Main Kitchen",
    name: "Premium Coffee Beans",
    description: "Arabica beans, medium roast, 1kg bags",
    unit: "kg",
    quantityRequested: 25,
    quantityApproved: 20,
    inventoryInfo: {
      onHand: 15,
      onOrdered: 30,
      lastPrice: 14.50,
      lastOrderDate: new Date("2023-05-10"),
      lastVendor: "Global F&B Suppliers",
      reorderLevel: 20,
      restockLevel: 80,
      averageMonthlyUsage: 45,
      inventoryUnit: "kg",
    },
    currency: "USD",
    price: 15.50,
    totalAmount: 310.00,
    status: "Approved",
    taxRate: 0.10,
    taxAmount: 31.00,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 341.00,
    deliveryDate: new Date("2023-07-01"),
    deliveryPoint: "Main Kitchen Storage",
    jobCode: "FB-2023-001",
    createdDate: new Date("2023-06-01"),
    updatedDate: new Date("2023-06-15"),
    createdBy: "John Chef",
    updatedBy: "Jane Manager",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Beverages",
    vendor: "Global F&B Suppliers",
    pricelistNumber: "PL-2023-06-FB",
    comment: "For breakfast and meeting services",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "FB-1001",
    baseSubTotalPrice: 310.00,
    subTotalPrice: 310.00,
    baseNetAmount: 341.00,
    baseDiscAmount: 0,
    baseTaxAmount: 31.00,
    baseTotalAmount: 310.00,
  },
  {
    id: "PR-2023-001-02",
    location: "Dry Storage",
    name: "All Purpose Flour",
    description: "Premium quality baking flour, 25kg sacks",
    unit: "kg",
    quantityRequested: 100,
    quantityApproved: 100,
    inventoryInfo: {
      onHand: 50,
      onOrdered: 200,
      lastPrice: 2.80,
      lastOrderDate: new Date("2023-05-15"),
      lastVendor: "Baking Supplies Co.",
      reorderLevel: 75,
      restockLevel: 300,
      averageMonthlyUsage: 120,
      inventoryUnit: "kg",
    },
    currency: "USD",
    price: 3.00,
    totalAmount: 300.00,
    status: "Review",
    taxRate: 0.08,
    taxAmount: 24.00,
    discountRate: 0.05,
    discountAmount: 15.00,
    netAmount: 309.00,
    deliveryDate: new Date("2023-07-03"),
    deliveryPoint: "Dry Storage Area",
    jobCode: "FB-2023-002",
    createdDate: new Date("2023-06-02"),
    updatedDate: new Date("2023-06-16"),
    createdBy: "Alice Baker",
    updatedBy: "Bob Supervisor",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Dry Goods",
    vendor: "Baking Supplies Co.",
    pricelistNumber: "PL-2023-06-BAKE",
    comment: "For daily bread and pastry production",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "FB-2001",
    baseSubTotalPrice: 300.00,
    subTotalPrice: 300.00,
    baseNetAmount: 309.00,
    baseDiscAmount: 15.00,
    baseTaxAmount: 24.00,
    baseTotalAmount: 300.00,
  },
  {
    id: "PR-2023-001-03",
    location: "Cold Storage",
    name: "Fresh Atlantic Salmon",
    description: "Premium salmon fillets, fresh daily delivery",
    unit: "kg",
    quantityRequested: 20,
    quantityApproved: 18,
    inventoryInfo: {
      onHand: 5,
      onOrdered: 25,
      lastPrice: 22.00,
      lastOrderDate: new Date("2023-06-10"),
      lastVendor: "Ocean Fresh Seafood",
      reorderLevel: 10,
      restockLevel: 30,
      averageMonthlyUsage: 35,
      inventoryUnit: "kg",
    },
    currency: "USD",
    price: 24.50,
    totalAmount: 441.00,
    status: "Approved",
    taxRate: 0.10,
    taxAmount: 44.10,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 485.10,
    deliveryDate: new Date("2023-07-02"),
    deliveryPoint: "Cold Storage Room B",
    jobCode: "FB-2023-003",
    createdDate: new Date("2023-06-03"),
    updatedDate: new Date("2023-06-17"),
    createdBy: "Mike Fishmonger",
    updatedBy: "Sarah Manager",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Seafood",
    vendor: "Ocean Fresh Seafood",
    pricelistNumber: "PL-2023-06-SEA",
    comment: "For special dinner menu and catering events",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "FB-3001",
    baseSubTotalPrice: 441.00,
    subTotalPrice: 441.00,
    baseNetAmount: 485.10,
    baseDiscAmount: 0,
    baseTaxAmount: 44.10,
    baseTotalAmount: 441.00,
  },
  {
    id: "PR-2023-001-04",
    location: "Housekeeping Storage",
    name: "Premium Bath Towels",
    description: "100% cotton, 600 GSM, white, hotel grade",
    unit: "piece",
    quantityRequested: 50,
    quantityApproved: 45,
    inventoryInfo: {
      onHand: 20,
      onOrdered: 100,
      lastPrice: 18.00,
      lastOrderDate: new Date("2023-05-20"),
      lastVendor: "Hotel Linen Co.",
      reorderLevel: 30,
      restockLevel: 100,
      averageMonthlyUsage: 25,
      inventoryUnit: "piece",
    },
    currency: "USD",
    price: 19.50,
    totalAmount: 877.50,
    status: "Review",
    taxRate: 0.08,
    taxAmount: 70.20,
    discountRate: 0.10,
    discountAmount: 87.75,
    netAmount: 859.95,
    deliveryDate: new Date("2023-07-05"),
    deliveryPoint: "Housekeeping Main Storage",
    jobCode: "HK-2023-001",
    createdDate: new Date("2023-06-04"),
    updatedDate: new Date("2023-06-18"),
    createdBy: "Lisa Housekeeper",
    updatedBy: "Tom Supervisor",
    itemCategory: "Housekeeping",
    itemSubcategory: "Linens",
    vendor: "Hotel Linen Co.",
    pricelistNumber: "PL-2023-06-LINEN",
    comment: "Replacement for worn towels in guest rooms",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "HK-1001",
    baseSubTotalPrice: 877.50,
    subTotalPrice: 877.50,
    baseNetAmount: 859.95,
    baseDiscAmount: 87.75,
    baseTaxAmount: 70.20,
    baseTotalAmount: 877.50,
  },
  {
    id: "PR-2023-001-05",
    location: "Maintenance Workshop",
    name: "LED Light Bulbs",
    description: "Energy efficient LED bulbs, 60W equivalent, warm white",
    unit: "piece",
    quantityRequested: 100,
    quantityApproved: 80,
    inventoryInfo: {
      onHand: 25,
      onOrdered: 150,
      lastPrice: 8.50,
      lastOrderDate: new Date("2023-04-25"),
      lastVendor: "Electrical Supplies Inc.",
      reorderLevel: 50,
      restockLevel: 200,
      averageMonthlyUsage: 60,
      inventoryUnit: "piece",
    },
    currency: "USD",
    price: 9.00,
    totalAmount: 720.00,
    status: "Approved",
    taxRate: 0.08,
    taxAmount: 57.60,
    discountRate: 0.15,
    discountAmount: 108.00,
    netAmount: 669.60,
    deliveryDate: new Date("2023-07-04"),
    deliveryPoint: "Maintenance Storage Room",
    jobCode: "MAINT-2023-001",
    createdDate: new Date("2023-06-05"),
    updatedDate: new Date("2023-06-19"),
    createdBy: "David Electrician",
    updatedBy: "Mark Supervisor",
    itemCategory: "Maintenance",
    itemSubcategory: "Electrical",
    vendor: "Electrical Supplies Inc.",
    pricelistNumber: "PL-2023-06-ELEC",
    comment: "Upgrade to energy-efficient lighting throughout property",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "MAINT-1001",
    baseSubTotalPrice: 720.00,
    subTotalPrice: 720.00,
    baseNetAmount: 669.60,
    baseDiscAmount: 108.00,
    baseTaxAmount: 57.60,
    baseTotalAmount: 720.00,
  },
  {
    id: "PR-2023-001-06",
    location: "Bar Storage",
    name: "Premium Whiskey Collection",
    description: "Single malt whiskey selection for VIP guests",
    unit: "bottle",
    quantityRequested: 12,
    quantityApproved: 0,
    inventoryInfo: {
      onHand: 3,
      onOrdered: 0,
      lastPrice: 125.00,
      lastOrderDate: new Date("2023-04-15"),
      lastVendor: "Premium Spirits Ltd.",
      reorderLevel: 8,
      restockLevel: 20,
      averageMonthlyUsage: 15,
      inventoryUnit: "bottle",
    },
    currency: "USD",
    price: 135.00,
    totalAmount: 1620.00,
    status: "Pending",
    taxRate: 0.12,
    taxAmount: 194.40,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 1814.40,
    deliveryDate: new Date("2023-07-10"),
    deliveryPoint: "Bar Storage Room",
    jobCode: "BAR-2023-001",
    createdDate: new Date("2023-06-06"),
    updatedDate: new Date("2023-06-06"),
    createdBy: "Emma Bartender",
    updatedBy: "Emma Bartender",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Spirits",
    vendor: "Premium Spirits Ltd.",
    pricelistNumber: "PL-2023-06-SPIRITS",
    comment: "Requested for upcoming VIP events and special occasions",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "BAR-1001",
    baseSubTotalPrice: 1620.00,
    subTotalPrice: 1620.00,
    baseNetAmount: 1814.40,
    baseDiscAmount: 0,
    baseTaxAmount: 194.40,
    baseTotalAmount: 1620.00,
  },
  {
    id: "PR-2023-001-07",
    location: "Front Desk Storage",
    name: "RFID Key Cards",
    description: "Hotel access cards with magnetic stripe backup",
    unit: "pack",
    quantityRequested: 20,
    quantityApproved: 0,
    inventoryInfo: {
      onHand: 8,
      onOrdered: 0,
      lastPrice: 45.00,
      lastOrderDate: new Date("2023-03-20"),
      lastVendor: "SecureAccess Systems",
      reorderLevel: 10,
      restockLevel: 30,
      averageMonthlyUsage: 12,
      inventoryUnit: "pack",
    },
    currency: "USD",
    price: 48.00,
    totalAmount: 960.00,
    status: "Pending",
    taxRate: 0.08,
    taxAmount: 76.80,
    discountRate: 0.05,
    discountAmount: 48.00,
    netAmount: 988.80,
    deliveryDate: new Date("2023-07-08"),
    deliveryPoint: "Front Desk Storage",
    jobCode: "FO-2023-001",
    createdDate: new Date("2023-06-07"),
    updatedDate: new Date("2023-06-07"),
    createdBy: "Rachel Receptionist",
    updatedBy: "Rachel Receptionist",
    itemCategory: "Front Office",
    itemSubcategory: "Access Control",
    vendor: "SecureAccess Systems",
    pricelistNumber: "PL-2023-06-SECURITY",
    comment: "Running low on key cards, need restock before summer season",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "FO-1001",
    baseSubTotalPrice: 960.00,
    subTotalPrice: 960.00,
    baseNetAmount: 988.80,
    baseDiscAmount: 48.00,
    baseTaxAmount: 76.80,
    baseTotalAmount: 960.00,
  },
  {
    id: "PR-2023-001-08",
    location: "Restaurant Kitchen",
    name: "Professional Chef Knives Set",
    description: "High-carbon stainless steel knife set with storage block",
    unit: "set",
    quantityRequested: 3,
    quantityApproved: 0,
    inventoryInfo: {
      onHand: 1,
      onOrdered: 0,
      lastPrice: 280.00,
      lastOrderDate: new Date("2023-02-10"),
      lastVendor: "Professional Kitchen Supply",
      reorderLevel: 2,
      restockLevel: 5,
      averageMonthlyUsage: 1,
      inventoryUnit: "set",
    },
    currency: "USD",
    price: 295.00,
    totalAmount: 885.00,
    status: "Pending",
    taxRate: 0.08,
    taxAmount: 70.80,
    discountRate: 0,
    discountAmount: 0,
    netAmount: 955.80,
    deliveryDate: new Date("2023-07-12"),
    deliveryPoint: "Kitchen Equipment Storage",
    jobCode: "KITCHEN-2023-001",
    createdDate: new Date("2023-06-08"),
    updatedDate: new Date("2023-06-08"),
    createdBy: "Carlos Chef",
    updatedBy: "Carlos Chef",
    itemCategory: "Food & Beverage",
    itemSubcategory: "Kitchen Equipment",
    vendor: "Professional Kitchen Supply",
    pricelistNumber: "PL-2023-06-KITCHEN",
    comment: "Additional knife sets needed for new kitchen staff",
    adjustments: {
      discount: false,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "KITCHEN-1001",
    baseSubTotalPrice: 885.00,
    subTotalPrice: 885.00,
    baseNetAmount: 955.80,
    baseDiscAmount: 0,
    baseTaxAmount: 70.80,
    baseTotalAmount: 885.00,
  },
  {
    id: "PR-2023-001-09",
    location: "Pool Area Storage",
    name: "Pool Cleaning Chemicals",
    description: "Chlorine tablets, pH balancers, and algae treatment",
    unit: "kit",
    quantityRequested: 5,
    quantityApproved: 0,
    inventoryInfo: {
      onHand: 2,
      onOrdered: 0,
      lastPrice: 85.00,
      lastOrderDate: new Date("2023-05-05"),
      lastVendor: "Pool Maintenance Co.",
      reorderLevel: 3,
      restockLevel: 10,
      averageMonthlyUsage: 8,
      inventoryUnit: "kit",
    },
    currency: "USD",
    price: 92.00,
    totalAmount: 460.00,
    status: "Pending",
    taxRate: 0.08,
    taxAmount: 36.80,
    discountRate: 0.10,
    discountAmount: 46.00,
    netAmount: 450.80,
    deliveryDate: new Date("2023-07-06"),
    deliveryPoint: "Pool Equipment Room",
    jobCode: "POOL-2023-001",
    createdDate: new Date("2023-06-09"),
    updatedDate: new Date("2023-06-09"),
    createdBy: "Steve Pool Attendant",
    updatedBy: "Steve Pool Attendant",
    itemCategory: "Maintenance",
    itemSubcategory: "Pool Supplies",
    vendor: "Pool Maintenance Co.",
    pricelistNumber: "PL-2023-06-POOL",
    comment: "Essential for maintaining pool water quality during peak season",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "POOL-1001",
    baseSubTotalPrice: 460.00,
    subTotalPrice: 460.00,
    baseNetAmount: 450.80,
    baseDiscAmount: 46.00,
    baseTaxAmount: 36.80,
    baseTotalAmount: 460.00,
  },
  {
    id: "PR-2023-001-10",
    location: "Laundry Room",
    name: "Commercial Laundry Detergent",
    description: "Heavy-duty detergent for hotel linens, 20kg drums",
    unit: "drum",
    quantityRequested: 8,
    quantityApproved: 0,
    inventoryInfo: {
      onHand: 3,
      onOrdered: 0,
      lastPrice: 65.00,
      lastOrderDate: new Date("2023-04-30"),
      lastVendor: "Industrial Cleaning Supplies",
      reorderLevel: 5,
      restockLevel: 15,
      averageMonthlyUsage: 10,
      inventoryUnit: "drum",
    },
    currency: "USD",
    price: 68.00,
    totalAmount: 544.00,
    status: "Pending",
    taxRate: 0.08,
    taxAmount: 43.52,
    discountRate: 0.08,
    discountAmount: 43.52,
    netAmount: 543.52,
    deliveryDate: new Date("2023-07-07"),
    deliveryPoint: "Laundry Storage Area",
    jobCode: "LAUNDRY-2023-001",
    createdDate: new Date("2023-06-10"),
    updatedDate: new Date("2023-06-10"),
    createdBy: "Maria Laundry Supervisor",
    updatedBy: "Maria Laundry Supervisor",
    itemCategory: "Housekeeping",
    itemSubcategory: "Cleaning Supplies",
    vendor: "Industrial Cleaning Supplies",
    pricelistNumber: "PL-2023-06-CLEAN",
    comment: "Need to restock before busy summer period begins",
    adjustments: {
      discount: true,
      tax: true,
    },
    taxIncluded: false,
    currencyRate: 1,
    foc: 0,
    accountCode: "LAUNDRY-1001",
    baseSubTotalPrice: 544.00,
    subTotalPrice: 544.00,
    baseNetAmount: 543.52,
    baseDiscAmount: 43.52,
    baseTaxAmount: 43.52,
    baseTotalAmount: 544.00,
  },
];