import { PurchaseRequest, PRType, DocumentStatus, WorkflowStatus, WorkflowStage } from '@/lib/types'


export const samplePRData: PurchaseRequest = {
  id: 'sample-pr-001',
  refNumber: 'PR-2023-001',
  date: new Date('2023-01-01'),
  type: PRType.GeneralPurchase,
  description: 'Sample purchase request for office supplies',
  requestorId: 'user-001',
  requestor: {
    name: 'John Doe',
    id: 'user-001',
    department: 'Administration'
  },
  status: DocumentStatus.Draft,
  workflowStatus: WorkflowStatus.pending,
  currentWorkflowStage: WorkflowStage.requester,
  location: 'Head Office',
  department: 'Administration',
  jobCode: 'JOB-001',
  estimatedTotal: 1500,
  vendor: 'Office Supplies Co.',
  vendorId: 1,
  deliveryDate: new Date('2023-01-15'),
  currency: 'USD',
  baseCurrencyCode: 'USD',
  baseSubTotalPrice: 1000,
  subTotalPrice: 1000,
  baseNetAmount: 1000,
  netAmount: 1000,
  baseDiscAmount: 0,
  discountAmount: 0,
  baseTaxAmount: 100,
  taxAmount: 100,
  baseTotalAmount: 1100,
  totalAmount: 1100,
  items: [
    {
      id: 'item-001',
      status: 'Pending',
      location: 'Head Office',
      name: 'Office Paper',
      description: 'A4 printer paper, 80gsm',
      unit: 'Box',
      quantityRequested: 10,
      quantityApproved: 0,
      deliveryDate: new Date('2023-01-15'),
      deliveryPoint: 'Reception',
      currency: 'USD',
      currencyRate: 1,
      price: 24.99,
      foc: 0,
      netAmount: 249.90,
      adjustments: {
        discount: false,
        tax: true,
      },
      taxIncluded: false,
      discountRate: 0,
      discountAmount: 0,
      taxRate: 7,
      taxAmount: 17.49,
      totalAmount: 267.39,
      vendor: 'Office Supplies Co.',
      pricelistNumber: 'PL-001',
      comment: '',
      createdBy: 'user-001',
      createdDate: new Date('2023-01-01'),
      updatedBy: 'user-001',
      updatedDate: new Date('2023-01-01'),
      itemCategory: 'Office Supplies',
      itemSubcategory: 'Paper',
      inventoryInfo: {
        onHand: 5,
        onOrdered: 0,
        reorderLevel: 10,
        restockLevel: 20,
        averageMonthlyUsage: 15,
        lastPrice: 24.99,
        lastOrderDate: new Date('2022-12-15'),
        lastVendor: 'Office Supplies Co.',
        inventoryUnit: 'Box',
      },
      accountCode: 'ACC-001',
      jobCode: 'JOB-001',
      baseSubTotalPrice: 249.90,
      subTotalPrice: 249.90,
      baseNetAmount: 249.90,
      baseDiscAmount: 0,
      baseTaxAmount: 17.49,
      baseTotalAmount: 267.39,
    }
  ],
}