import { RecipeMapping } from "./types"

export const recipeMappings: RecipeMapping[] = [
  {
    id: "recipe-001",
    posItemCode: "POS001",
    posDescription: "Chicken Curry",
    recipeCode: "RCP001",
    recipeName: "Chicken Curry",
    posUnit: "Plate",
    recipeUnit: "Recipe",
    conversionRate: 1,
    category: "Main Course",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T15:30:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:00:00"),
    updatedAt: new Date("2023-11-20T15:45:00"),
    isActive: true,
  },
  {
    id: "recipe-002",
    posItemCode: "POS002",
    posDescription: "Vegetable Pasta",
    recipeCode: "RCP002",
    recipeName: "Vegetable Pasta",
    posUnit: "Plate",
    recipeUnit: "Recipe",
    conversionRate: 1,
    category: "Main Course",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T15:35:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:05:00"),
    updatedAt: new Date("2023-11-20T15:50:00"),
    isActive: true,
  },
  {
    id: "recipe-003",
    posItemCode: "POS003",
    posDescription: "Caesar Salad",
    recipeCode: "RCP003",
    recipeName: "Caesar Salad",
    posUnit: "Bowl",
    recipeUnit: "Recipe",
    conversionRate: 1,
    category: "Starters",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T15:40:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:10:00"),
    updatedAt: new Date("2023-11-20T15:55:00"),
    isActive: true,
  },
  {
    id: "recipe-004",
    posItemCode: "POS004",
    posDescription: "Margarita",
    recipeCode: "RCP004",
    recipeName: "Classic Margarita",
    posUnit: "Glass",
    recipeUnit: "Recipe",
    conversionRate: 1,
    category: "Beverages",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T15:45:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:15:00"),
    updatedAt: new Date("2023-11-20T16:00:00"),
    isActive: true,
  },
  // Enhanced fractional sales mappings - Chocolate Pound Cake variants
  {
    id: "recipe-005",
    posItemCode: "POS005",
    posDescription: "Chocolate Cake Slice",
    recipeCode: "chocolate-pound-cake",
    recipeName: "Chocolate Pound Cake",
    posUnit: "Slice",
    recipeUnit: "whole cake",
    conversionRate: 0.0625, // 1/16 of cake
    recipeVariantId: "cake-slice",
    variantName: "Cake Slice",
    baseRecipeId: "chocolate-pound-cake",
    fractionalSalesType: "cake-slice",
    category: "Desserts",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T15:50:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:20:00"),
    updatedAt: new Date("2023-11-20T16:05:00"),
    isActive: true,
  },
  {
    id: "recipe-005-quarter",
    posItemCode: "POS005Q",
    posDescription: "Quarter Chocolate Cake",
    recipeCode: "chocolate-pound-cake",
    recipeName: "Chocolate Pound Cake",
    posUnit: "Quarter",
    recipeUnit: "whole cake",
    conversionRate: 0.25, // 1/4 of cake
    recipeVariantId: "cake-quarter",
    variantName: "Quarter Cake",
    baseRecipeId: "chocolate-pound-cake",
    fractionalSalesType: "cake-slice",
    category: "Desserts",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T15:52:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:22:00"),
    updatedAt: new Date("2023-11-20T16:07:00"),
    isActive: true,
  },
  {
    id: "recipe-005-half",
    posItemCode: "POS005H",
    posDescription: "Half Chocolate Cake",
    recipeCode: "chocolate-pound-cake",
    recipeName: "Chocolate Pound Cake",
    posUnit: "Half",
    recipeUnit: "whole cake",
    conversionRate: 0.5, // 1/2 of cake
    recipeVariantId: "cake-half",
    variantName: "Half Cake",
    baseRecipeId: "chocolate-pound-cake",
    fractionalSalesType: "cake-slice",
    category: "Desserts",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T15:54:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:24:00"),
    updatedAt: new Date("2023-11-20T16:09:00"),
    isActive: true,
  },
  {
    id: "recipe-005-whole",
    posItemCode: "POS005W",
    posDescription: "Whole Chocolate Cake",
    recipeCode: "chocolate-pound-cake",
    recipeName: "Chocolate Pound Cake",
    posUnit: "Whole",
    recipeUnit: "whole cake",
    conversionRate: 1.0, // Full cake
    recipeVariantId: "cake-whole",
    variantName: "Whole Cake",
    baseRecipeId: "chocolate-pound-cake",
    fractionalSalesType: "cake-slice",
    category: "Desserts",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T15:56:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:26:00"),
    updatedAt: new Date("2023-11-20T16:11:00"),
    isActive: true,
  },
  {
    id: "recipe-006",
    posItemCode: "POS006",
    posDescription: "French Fries",
    recipeCode: "",
    recipeName: "",
    posUnit: "Portion",
    recipeUnit: "",
    conversionRate: 0,
    category: "Sides",
    status: "unmapped",
    createdAt: new Date("2023-01-15T10:25:00"),
    updatedAt: new Date("2023-01-15T10:25:00"),
    isActive: true,
  },
  {
    id: "recipe-007",
    posItemCode: "POS007",
    posDescription: "Cappuccino",
    recipeCode: "RCP007",
    recipeName: "Cappuccino",
    posUnit: "Cup",
    recipeUnit: "Recipe",
    conversionRate: 1,
    category: "Beverages",
    status: "error",
    lastSyncDate: new Date("2023-11-15T09:30:00"),
    lastSyncStatus: "error",
    createdAt: new Date("2023-01-15T10:30:00"),
    updatedAt: new Date("2023-11-15T09:35:00"),
    isActive: false,
  },
  {
    id: "recipe-008",
    posItemCode: "POS008",
    posDescription: "Club Sandwich",
    recipeCode: "RCP008",
    recipeName: "Club Sandwich",
    posUnit: "Piece",
    recipeUnit: "Recipe",
    conversionRate: 1,
    category: "Snacks",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T15:55:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:35:00"),
    updatedAt: new Date("2023-11-20T16:10:00"),
    isActive: true,
  },
  // Enhanced fractional sales mappings - Margherita Pizza variants
  {
    id: "recipe-009",
    posItemCode: "POS009",
    posDescription: "Pizza Slice - Margherita",
    recipeCode: "margherita-pizza",
    recipeName: "Margherita Pizza",
    posUnit: "Slice",
    recipeUnit: "large pizza",
    conversionRate: 0.125, // 1/8 of pizza
    recipeVariantId: "pizza-slice",
    variantName: "Pizza Slice",
    baseRecipeId: "margherita-pizza",
    fractionalSalesType: "pizza-slice",
    category: "Main Course",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T16:00:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:40:00"),
    updatedAt: new Date("2023-11-20T16:15:00"),
    isActive: true,
  },
  {
    id: "recipe-009-half",
    posItemCode: "POS009H",
    posDescription: "Half Pizza - Margherita",
    recipeCode: "margherita-pizza",
    recipeName: "Margherita Pizza",
    posUnit: "Half",
    recipeUnit: "large pizza",
    conversionRate: 0.5, // 1/2 of pizza
    recipeVariantId: "pizza-half",
    variantName: "Half Pizza",
    baseRecipeId: "margherita-pizza",
    fractionalSalesType: "pizza-slice",
    category: "Main Course",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T16:02:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:42:00"),
    updatedAt: new Date("2023-11-20T16:17:00"),
    isActive: true,
  },
  {
    id: "recipe-009-whole",
    posItemCode: "POS009W",
    posDescription: "Whole Pizza - Margherita",
    recipeCode: "margherita-pizza",
    recipeName: "Margherita Pizza",
    posUnit: "Whole",
    recipeUnit: "large pizza",
    conversionRate: 1.0, // Full pizza
    recipeVariantId: "pizza-whole",
    variantName: "Whole Pizza",
    baseRecipeId: "margherita-pizza",
    fractionalSalesType: "pizza-slice",
    category: "Main Course",
    status: "mapped",
    lastSyncDate: new Date("2023-12-01T16:04:00"),
    lastSyncStatus: "active",
    createdAt: new Date("2023-01-15T10:44:00"),
    updatedAt: new Date("2023-11-20T16:19:00"),
    isActive: true,
  },
]

export const categories = [
  { id: "main-course", name: "Main Course" },
  { id: "starters", name: "Starters" },
  { id: "beverages", name: "Beverages" },
  { id: "desserts", name: "Desserts" },
  { id: "sides", name: "Sides" },
  { id: "snacks", name: "Snacks" },
]

export const locations = [
  { id: "loc-001", name: "Main Restaurant" },
  { id: "loc-002", name: "Lobby Bar" },
  { id: "loc-003", name: "Pool Bar" },
  { id: "loc-004", name: "Rooftop Lounge" },
  { id: "loc-005", name: "Beach Restaurant" },
] 